# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 838)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1121, 61))
        self.label.setStyleSheet("QFrame\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 760, 1121, 32))
        self.frame.setStyleSheet("QFrame\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(310, 60, 811, 701))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 809, 699))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(63, 113, 184, 229))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Auto_cut = QtWidgets.QPushButton(self.layoutWidget)
        self.Auto_cut.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 1, y1: 1, x2: 1, y2: 0, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.Auto_cut.setObjectName("Auto_cut")
        self.verticalLayout.addWidget(self.Auto_cut)
        self.Process = QtWidgets.QPushButton(self.layoutWidget)
        self.Process.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 1, y1: 1, x2: 1, y2: 0, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.Process.setObjectName("Process")
        self.verticalLayout.addWidget(self.Process)
        self.Stop_process = QtWidgets.QPushButton(self.layoutWidget)
        self.Stop_process.setMaximumSize(QtCore.QSize(171, 16777215))
        self.Stop_process.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 1, y1: 1, x2: 1, y2: 0, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.Stop_process.setObjectName("Stop_process")
        self.verticalLayout.addWidget(self.Stop_process)
        self.Select_image = QtWidgets.QPushButton(self.layoutWidget)
        self.Select_image.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 1, y1: 1, x2: 1, y2: 0, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.Select_image.setObjectName("Select_image")
        self.verticalLayout.addWidget(self.Select_image)
        self.Present_images = QtWidgets.QPushButton(self.layoutWidget)
        self.Present_images.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 1, y1: 1, x2: 1, y2: 0, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.Present_images.setObjectName("Present_images")
        self.verticalLayout.addWidget(self.Present_images)
        self.clip_rate = QtWidgets.QProgressBar(self.centralwidget)
        self.clip_rate.setGeometry(QtCore.QRect(70, 540, 211, 23))
        self.clip_rate.setStyleSheet("QProgressBar::chunk\n"
"{\n"
"border-radius:11px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:1,y2:0,stop:0 #01FAFF,stop:1  #26B4FF);\n"
"}\n"
"QProgressBar#progressBar\n"
"{\n"
"height:22px;\n"
"text-align:center;/*文本位置*/\n"
"font-size:14px;\n"
"color:white;\n"
"border-radius:11px;\n"
"background: #1D5573 ;\n"
"}")
        self.clip_rate.setProperty("value", 24)
        self.clip_rate.setObjectName("clip_rate")
        self.process_rate = QtWidgets.QProgressBar(self.centralwidget)
        self.process_rate.setGeometry(QtCore.QRect(70, 440, 211, 23))
        self.process_rate.setStyleSheet("QProgressBar::chunk\n"
"{\n"
"border-radius:11px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:1,y2:0,stop:0 #01FAFF,stop:1  #26B4FF);\n"
"}\n"
"QProgressBar#progressBar\n"
"{\n"
"height:22px;\n"
"text-align:center;/*文本位置*/\n"
"font-size:14px;\n"
"color:white;\n"
"border-radius:11px;\n"
"background: #1D5573 ;\n"
"}")
        self.process_rate.setProperty("value", 24)
        self.process_rate.setObjectName("process_rate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 400, 221, 21))
        self.label_2.setStyleSheet("self.setStyleSheet(\"QLabel{background:white;}\"\n"
"                   \"QLabel{color:rgb(100,100,100,250);font-size:15px;font-weight:bold;font-family:Roman times;}\"\n"
"                   \"QLabel:hover{color:rgb(100,100,100,120);}\")")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 500, 201, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.menu.addAction(self.actionOpen_file)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Video processor</span></p></body></html>"))
        self.Auto_cut.setText(_translate("MainWindow", "Auto cut"))
        self.Process.setText(_translate("MainWindow", "Process"))
        self.Stop_process.setText(_translate("MainWindow", "Stop processing"))
        self.Select_image.setText(_translate("MainWindow", "Select meaningless frame"))
        self.Present_images.setText(_translate("MainWindow", "Present the images"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#aa55ff;\">处理进度</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#aa55ff;\">剪辑进度</span></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file"))
