# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_pic.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(40, 30, 721, 501))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 719, 499))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.num_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.num_1.setGeometry(QtCore.QRect(120, 180, 113, 20))
        self.num_1.setObjectName("num_1")
        self.num_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.num_2.setGeometry(QtCore.QRect(360, 180, 113, 20))
        self.num_2.setObjectName("num_2")
        self.Plus = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Plus.setGeometry(QtCore.QRect(270, 130, 75, 23))
        self.Plus.setObjectName("Plus")
        self.sum = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.sum.setGeometry(QtCore.QRect(240, 260, 113, 20))
        self.sum.setObjectName("sum")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Plus.setText(_translate("MainWindow", "相加"))
