# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1053, 708)
        self.btn_select = QtWidgets.QPushButton(Form)
        self.btn_select.setGeometry(QtCore.QRect(280, 510, 131, 61))
        self.btn_select.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.btn_select.setObjectName("btn_select")
        self.wgt_player = QVideoWidget(Form)
        self.wgt_player.setGeometry(QtCore.QRect(0, 0, 1051, 411))
        self.wgt_player.setObjectName("wgt_player")
        self.btn_play_pause = QtWidgets.QPushButton(Form)
        self.btn_play_pause.setGeometry(QtCore.QRect(470, 510, 141, 61))
        self.btn_play_pause.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.btn_play_pause.setObjectName("btn_play_pause")
        self.sld_duration = QtWidgets.QSlider(Form)
        self.sld_duration.setGeometry(QtCore.QRect(99, 450, 851, 22))
        self.sld_duration.setStyleSheet("QSlider::groove:horizontal {\n"
"  border: 0px solid #bbb;\n"
"}\n"
" \n"
"QSlider::sub-page:horizontal {\n"
"  background: rgb(255,255,0);\n"
"  border-radius: 0px;\n"
"  margin-top: 8px;\n"
"  margin-bottom: 9px;\n"
"}\n"
" \n"
"QSlider::add-page:horizontal {\n"
"  background: rgb(0,0,0);\n"
"  border: 0px solid #777; \n"
"  border-radius: 2px; \n"
"  margin-top: 8px; \n"
"  margin-bottom: 9px; \n"
"}\n"
" \n"
"QSlider::handle:horizontal { \n"
"  background: rgb(255,255,255); \n"
"  border: 1px solid rgba(102,102,102,102); \n"
"  width: 8px; \n"
"  height: 8px; \n"
"  border-radius: 5px; \n"
"  margin-top: 2px; \n"
"  margin-bottom: 2px; \n"
"}\n"
" \n"
"QSlider::handle:horizontal:hover { \n"
"  background: rgb(255,255,0); \n"
"  border: 1px solid rgba(102,102,102,102); \n"
"  border-radius: 5px; \n"
"}\n"
" \n"
"QSlider::sub-page:horizontal:disabled { \n"
"  background: #bbb; \n"
"  border-color: #999; \n"
"}\n"
" \n"
"QSlider::add-page:horizontal:disabled { \n"
"  background: #eee; \n"
"  border-color: #999; \n"
"}\n"
" \n"
"QSlider::handle:horizontal:disabled { \n"
"  background: #eee; \n"
"  border: 1px solid #aaa; \n"
"  border-radius: 4px; \n"
"}")
        self.sld_duration.setOrientation(QtCore.Qt.Horizontal)
        self.sld_duration.setObjectName("sld_duration")
        self.lab_duration = QtWidgets.QLabel(Form)
        self.lab_duration.setGeometry(QtCore.QRect(970, 440, 41, 31))
        self.lab_duration.setObjectName("lab_duration")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_select.setText(_translate("Form", "播放视频"))
        self.btn_play_pause.setText(_translate("Form", "Stop"))
        self.lab_duration.setText(_translate("Form", "--/--"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
